version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: openpmdb

  portal:
    container_name: portal
    build:
      context: pe-portal/
      dockerfile: Dockerfile
    volumes:
      - pe-portal/:/app
      - /app/node_modules
    ports:
      - 4200:4200

  server:
    container_name: pe-server
    build:
      context: pe-server/
      dockerfile: Dockerfile
    volumes:
      - pe-server/:/app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/openpmdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test123
    depends_on:
      - postgresql

volumes:
  pe-portal: {}
  pe-server: {}